const api = {
  Login: '/user/login',
  queryMyOwlList: '/owl/queryMyOwlList',
  feedMyOwls: '/owl/feedMyOwls',
  queryMyFriends: '/user/queryMyFriends',
  getIndexInfo: '/account/getIndexInfo',
  queryPalaceOwls:'/owl/queryPalaceOwls',
  queryIncomeList:'/account/queryIncomeList',
  queryNoticeList:'/notice/queryNoticeList',
  readNoticeContent:'/notice/readNoticeContent',
  createBuyOwlOrder:'/owl/createBuyOwlOrder',
  getPlayWay:'/notice/getPlayWay',
  queryWalletList:'/wallet/queryWalletList',
  queryWithdrawList:'/account/queryWithdrawList',
  payOwlOrder:'/owl/payOwlOrder',
  getdraw:'/owl/draw',
  withdrawIncome:'/account/withdrawIncome',
  verifyZjadReward:'/account/verifyZjadReward',
  updateName:'/user/updateName',
  queryTransaction:'/wallet/queryTransaction',
  queryMyTeamOwl:'/owl/queryMyTeamOwl',
  checkIdct:'/user/check',
}

export default api
